version: "3"

services:
  web:
    image: vue-material
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:    
